In [1]:
import numpy as np

In [2]:
a=[10,20,30,40]
type(a)

list

In [5]:
arr=np.array(a) #ndarray
type(arr)

numpy.ndarray

In [8]:
arr.max() #arr. 하고 Tab키 누르면 사용가능한 함수 나옴

40

In [9]:
b=[[1,2,3,4],[5,6,7,8]]
arrb=np.array(b)
arrb.ndim

2

In [10]:
arrb.dtype

dtype('int32')

In [13]:
float_arr=arrb.astype(np.float32)
float_arr.dtype

dtype('float32')

In [14]:
for i in np.arange(10):
    print(i)

0
1
2
3
4
5
6
7
8
9


In [17]:
arrList = np.arange(10)
type(arrList)

numpy.ndarray

In [18]:
arrList

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
a[0]
b[0][1] #일반 리스트는 b[0,1] 이런표기 지원하지 X

2

In [24]:
arr2d = np.array([[1,2,3],[4,5,6]])
arr2d.shape
arr2d[0,2]

3

In [25]:
arr2d[0,2]=30
arr2d

array([[ 1,  2, 30],
       [ 4,  5,  6]])

In [28]:
arr2d_cp = arr2d #ndarray 복사
arr2d_cp.shape #모양확인
arr2d_cp

array([[ 1,  2, 30],
       [ 4,  5,  6]])

In [37]:
arr2d[0,2]=300 # 이렇게 했을 때 arr2d랑 arr2d_cp 둘다 (0,2) 값이 300으로 바뀜 (주의!)
print(arr2d)
print(arr2d_cp)

[[  1   2 300]
 [  4   5   6]]
[[  1   2 300]
 [  4   5   6]]


In [36]:
arr2d_cp2 = arr2d.copy() # 깊은복사, 값도 메모리를 따로 만들어서 복사하라는 것
arr2d_cp2[0,2] = 3000
print(arr2d_cp)
print(arr2d_cp2)

[[  1   2 300]
 [  4   5   6]]
[[   1    2 3000]
 [   4    5    6]]


In [40]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
names.dtype

names =='Bob'

array([ True, False, False,  True, False, False, False])

In [46]:
data=np.arange(7)
data

array([0, 1, 2, 3, 4, 5, 6])

In [45]:
data[names == 'Bob']

array([0, 3])

In [47]:
data[names != 'Bob']

array([1, 2, 4, 5, 6])

In [48]:
data[(names=='Bob')|(names=='Will')]

array([0, 2, 3, 4])

In [51]:
arr=np.empty((8,4)) #(행,열)
for i in range(8): #[0,1,2,3,4,5,6,7]
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [60]:
#배열 중 5,4,1,7 행만 추출
arr[5,]
arr[(5,4,1,7),]
arr[[5,4,1,7],]

array([[5., 5., 5., 5.],
       [4., 4., 4., 4.],
       [1., 1., 1., 1.],
       [7., 7., 7., 7.]])

In [61]:
arr2 = np.arange(32).reshape((8,4))
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [62]:
arr2[[5,4,1,7],[3,1,0,2]]

array([23, 17,  4, 30])

In [68]:
arr2[[5,4,1,7]][:,[3,1,0,2]]

array([[23, 21, 20, 22],
       [19, 17, 16, 18],
       [ 7,  5,  4,  6],
       [31, 29, 28, 30]])

In [69]:
arr2[np.ix_([5,4,1,7],[3,1,0,2])]

array([[23, 21, 20, 22],
       [19, 17, 16, 18],
       [ 7,  5,  4,  6],
       [31, 29, 28, 30]])